hanka logged in successfully
Processing default request
hanka logged in successfully
Processing default request
hanka logged in successfully
2020-04-07 08:15:38,458 - app - INFO - hanka logged in successfully
2020-04-07 08:18:28,592 - app - ERROR - Exception on /login [POST]
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Python38\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Python38\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Program Files\Python38\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Python38\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 521, in login
    app.logger.errors("Error")
AttributeError: 'Logger' object has no attribute 'errors'
2020-04-07 08:18:51,762 - app - ERROR - Error
2020-04-07 08:24:23,230 - app - ERROR - Error
2020-04-07 08:26:30,416 - app - INFO - hanka logged in successfully
2020-04-07 08:26:30,417 - app - ERROR - Error
